---
title: "Customizing RESQUE"
toc: false
---

RESQUE advocates a "buffet table approach", where each committee can select and adjust the indicators that are relevant for them.
Currently, however, this customization of the [Collector App](https://resque-framework.github.io/collector-app) needs some technical expertise.

The selection of indicators itself (if you do not want to use the default core set) is done in the `/config/config.yaml` file of the [Collector App](https://github.com/RESQUE-Framework/collector-app). in that configuration, you can also adjust the text of the Welcome Screen, add the logo of your university, change the background color, and set the minimum and maximum number of publications an applicant may submit.

The easiest way to create a custom version of the app is to fork our repository on Github and make your changes in your personal copy. If you activate Github Pages, you will get a dedicated URL for the Collector App of your hiring committee (this could be, for example, `https://resque-framework.github.io/collector-app-eichstaett`). **This [manual](https://github.com/RESQUE-Framework/collector-app/blob/main/How_to_fork.md) explains how to create a fork step by step.**

We are happy to [assist](../team.qmd) in customizing the app for your hiring committee.
