---
title: "Computation of Relative Rigor Score (RRS)"
toc: false
---

## Basic Principles

There are many ways to conduct science, and RESQUE does not give a precedence to any approach. For example, it does not favor confirmatory research over exploratory research. But whatever approach you choose, it should be done well. So we created quality indicators for different aspects.

Importantly, you should not be penalized if certain points cannot be achieved in principle. Therefore, we compute the **Relative Rigor Scores** as a POMP (Percentage of Maximum Points): If an indicator is justifiably 'not applicable', the indicator is taken out of the set, the maximum score is adjusted accordingly, allowing for the possibility of achieving 100% of the applicable points.

## Equal weighting of research outputs

For the computation of the overall RRS score, all submitted research outputs are weighted equally. That means, if two publications are available, each publication contributes 50% to the overall score, even if they differ in their maximally attainable points. The reasoning is that it should not be punished if some points cannot be obtained in principle.
With our POMP ("percentage of maximum points") computation, it is ensured that the RRS for each research output can reach 100% even if some indicators are not applicable.
But if research outputs with less attainable points contribute less to the overall score, this would be a disadvantage. Therefore each output is weighted equally.

