---
title: "Commentaries by the scientific community"
toc: false
---

You can find 15 comments to our target papers [1](https://doi.org/10.31234/osf.io/rgh5b) and [2](https://doi.org/10.31234/osf.io/5yexm) published in [Meta-Psychology](https://open.lnu.se/index.php/metapsychology/issue/view/283):

- Brown, G. (2024). **A broader view of research contributions: Necessary adjustments to DORA for hiring and promotion in psychology.** *Meta-Psychology, 2024 (8)*, MP.2022.3652. [https://doi.org/10.15626/MP.2024](https://doi.org/10.15626/MP.2024)
- Sandoval-Lentisco, A. (2022). **Commentary: Responsible Research Assessment: Implementing DORA for hiring and promotion in psychology.** *Meta-Psychology, 2024 (8)*, MP.2022.3655. [https://doi.org/10.15626/MP.2022.3655](https://doi.org/10.15626/MP.2022.3655)
- Karhulahti, V. (2023). **Interdisciplinary value.** *Meta-Psychology, 2024 (8)*, MP.2023.3679. [https://doi.org/10.15626/MP.2023.3679]( https://doi.org/10.15626/MP.2023.3679)
- Witte, E. H. (2023). **Comment on: Responsible Research Assessment I and Responsible Research Assessment II.** *Meta-Psychology, 2024 (8)*, MP.2023.3685. [https://doi.org/10.15626/MP.2023.3685](https://doi.org/10.15626/MP.2023.3685)
- Stengelin, R., Bohn, M., Sanchez-Amaro, A., Haun, D., Thiele, M., Allritz, M., … Schuhmacher, N. (2023). **Responsible Research is also concerned with generalizability: Recognizing efforts to reflect upon and increase generalizability in hiring and promotion decisions in psychology.** *Meta-Psychology, 2024 (8)*, MP.2023.3695. [https://doi.org/10.15626/MP.2023.3695](https://doi.org/10.15626/MP.2023.3695)
- Brandmaier, A. M., Ernst, M. S., & Peikert, A. (2023). **Assessing rigor and impact of research software for hiring and promotion in psychology: A comment on Gärtner et al. (2022). *****Meta-Psychology, 2024 (8)*, MP.2023.3715. [https://doi.org/10.15626/MP.2023.3715](https://doi.org/10.15626/MP.2023.3715)
- Frischkorn, G. T. (2023). **Responsible Research Assessment requires structural more than procedural reforms.** *Meta-Psychology, 2024 (8)*, MP.2023.3734. [https://doi.org/10.15626/MP.2023.3734](https://doi.org/10.15626/MP.2023.3734)
- Dames, H., Musfeld, P., Popov, V., Oberauer, K., & Frischkorn, G. T. (2023). **Responsible Research Assessment Should Prioritize Theory Development and Testing Over Ticking Open Science Boxes.** *Meta-Psychology, 2024 (8)*, MP.2023.3735. [https://doi.org/10.15626/MP.2023.3735](https://doi.org/10.15626/MP.2023.3735)
- Syed, M. (2023). **Valuing Preprints Must be Part of Responsible Research Assessment.** *Meta-Psychology, 2024 (8)*, MP.2023.3758. [https://doi.org/10.15626/MP.2023.3758](https://doi.org/10.15626/MP.2023.3758)
- Hansen, M., Beitner, J., Horz, H., & Schultze, M. (2023). **Indicators for teaching assessment.** *Meta-Psychology, 2024 (8)*, MP.2023.3763. [https://doi.org/10.15626/MP.2023.3763](https://doi.org/10.15626/MP.2023.3763)
- Hostler, T. (2023). **Research assessment using a narrow definition of “research quality” is an act of gatekeeping: A comment on Gärtner et al. (2022). *****Meta-Psychology, 2024 (8)*, MP.2023.3764. [https://doi.org/10.15626/MP.2023.3764](https://doi.org/10.15626/MP.2023.3764)
- Auger, V., & Claes, N. (2023). **Comment on "Responsible Research Assessment: Implementing DORA for hiring and promotion in psychology”.** *Meta-Psychology, 2024 (8)*, MP.2023.3779. [https://doi.org/10.15626/MP.2023.3779](https://doi.org/10.15626/MP.2023.3779)
- Fink-Lamotte, J., Hilbert, K., Bentz, D., Blackwell, S. E., Boehnke, J. R., Burghardt, J., … Niemeyer, H. (2023). **Response to responsible research assessment I and II from the perspective of the DGPs working group on open science in clinical psychology.** *Meta-Psychology, 2024 (8)*, MP.2023.3794. [https://doi.org/10.15626/MP.2023.3794](https://doi.org/10.15626/MP.2023.3794)
- Brandt, H., Henninger, M., Ulitzsch, E., Kleinke, K., & Schäfer, T. (2023). **Responsible research assessment in the area of methodological or quantitative research: A comment on Gärtner et al. (2022). *****Meta-Psychology, 2024 (8)*, MP.2023.3796. [https://doi.org/10.15626/MP.2023.3796](https://doi.org/10.15626/MP.2023.3796)
- Ulpts, S. (2023). **Responsible assessment of what research? Beware of epistemic diversity!** *Meta-Psychology, 2024 (8)*, MP.2023.3797. [https://doi.org/10.15626/MP.2023.3797](https://doi.org/10.15626/MP.2023.3797)


Furthermore, there are 6 additional commentaries (in German) published in the [Psychologische Rundschau](https://econtent.hogrefe.com/toc/pru/74/3):

- Lange, J., Degner, J., Gleibs, I. H., & Jonas, E. (2023). **Fachgruppe Sozialpsychologie: Faires und valides Shortlisting in Phase 1.** *Psychologische Rundschau, 74(3)*, 187–190. [https://doi.org/10.1026/0033-3042/a000641](https://doi.org/10.1026/0033-3042/a000641)
- Niessen, C., Melchers, K. G., Ohly, S., Fay, D., Handke, L., & Kern, U. M. (2023). **Fachgruppe Arbeits-, Organisations- und Wirtschaftspsychologie: Ein Plädoyer für breit gewählte und anforderungsbezogene Leistungsindikatoren.** *Psychologische Rundschau, 74(3)*, 180–182. [https://doi.org/10.1026/0033-3042/a000637](https://doi.org/10.1026/0033-3042/a000637)
- Ortner, T., Kretzschmar, A., Rauthmann, J. F., & Tibubos, A. N. (2023). **Fachgruppe Differentielle Psychologie, Persönlichkeitspsychologie und psychologische Diagnostik: Berufungsverfahren unter einer diagnostischen Perspektive fundiert durchführen.** *Psychologische Rundschau, 74(3)*, 182–184. [https://doi.org/10.1026/0033-3042/a000638](https://doi.org/10.1026/0033-3042/a000638)
- Schwartz, B., Szota, K., Schmitz, J., Lueken, U., & Lincoln, T. (2023). **Fachgruppe Klinische Psychologie und Psychotherapie: Mehr Differenzierung nach Fachgebieten.** *Psychologische Rundschau, 74(3)*, 184–185. [https://doi.org/10.1026/0033-3042/a000639](https://doi.org/10.1026/0033-3042/a000639)
- Sparfeldt, J. R., Spörer, N., Greiff, S., & Schneider, R. (2023). **Fachgruppe Pädagogische Psychologie: Ein Plädoyer für valide‍(re) Bewertungen der wissenschaftlichen Leistungen in Berufungsverfahren.** *Psychologische Rundschau, 74(3)*, 185–187. [https://doi.org/10.1026/0033-3042/a000640](https://doi.org/10.1026/0033-3042/a000640)
- Stroebe, W., & Strack, F. (2023). Kommentare zu Gärtner, A. et al. (2023). **Empfehlungen zur Bewertung wissenschaftlicher Leistungen bei Berufungsverfahren in der Psychologie: Zweierlei Maß? Warum manche Psychologen den Gebrauch von quantitativen Indikatoren der Forschungsqualität ablehnen.** *Psychologische Rundschau, 74(3)*, 175–179. [https://doi.org/10.1026/0033-3042/a000631](https://doi.org/10.1026/0033-3042/a000631)
